image: node:13

pages:
  cache:
    paths:
    - node_modules/

  script:
  - npm install -g hexo-cli
  - npm install
  - npm install hexo-deployer-git --save
  - mkdir ~/.ssh && cp id_rsa ~/.ssh/id_rsa
  - git config --global user.email "root@wuchuheng.com"
  - git config --global user.name "wuchuheng"
  - echo StrictHostKeyChecking no >> /etc/ssh/ssh_config
  - hexo deploy
  artifacts:
    paths:
    - public
  only:
  - master
