image: node:9

pages:
  cache:
    paths:
    - node_modules/

  script:
  - npm install -g hexo-cli
  - npm install
  - npm install hexo-deployer-git --save
  - git config --global user.email "root@wuchuheng.com"
  - git config --global user.name "wuchuheng"
  - mkdir ~/.ssh/ && cp id_rsa ~/.ssh/ && chmod 600 ~/.ssh/id_rsa 
  - echo "StrictHostKeyChecking no" >> /etc/ssh/ssh_config
  - hexo d -g
  - echo "Deploy succssed!"

  artifacts:
    paths:
    - public
  only:
  - master
