image: node:9

pages:
  cache:
    paths:
    - node_modules/

  script:
  - npm install -g hexo-cli
  - npm install
  - npm install hexo-deployer-git --save
  - git config --global user.email "root@wuchuheng.com"
  - git config --global user.name "wuchuheng"
  - eval $(ssh-agent -s)
  - chmod 700 id_rsa
  - ssh-add id_rsa
  - echo "StrictHostKeyChecking no" >> /etc/ssh/ssh_config
  - hexo d -g
  - echo "Deploy succssed!"

  artifacts:
    paths:
    - public
  only:
  - master
