image: node:13.7.0-alpine3.10

pages:
  cache:
    paths:
    - node_modules/

  script:
  - npm install -g hexo-cli
  - npm install
  - hexo deploy
  artifacts:
    paths:
    - public
  only:
  - master
