image: node:13.7.0-alpine3.10

pages:
  cache:
    paths:
    - node_modules/

  script:
  - yarn add global hexo-cli
  - yarn install
  - hexo deploy
  artifacts:
    paths:
    - public
  only:
  - master
