image: node:8.11.2

pages:
  cache:
    paths:
    - node_modules/

  script:
  - npm install hexo-cli -g
  - npm install hexo-generator-searchdb --save
  - npm install hexo-nofollow --save 
  - npm install
  - hexo deploy
  artifacts:
    paths:
    - public
  only:
  - master
