sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS

# 指定缓存模块，可选。缓存可加快编译速度。
cache:
  directories:
    - node_modules

# 指定博客的仓库地址
env:
 global:
   # Github Pages
   - GH_REF: github.com/wuchuheng/wuchuheng.github.io.git
   # Coding Pages
   - CO_REF: e.coding.net/wuchuheng/wuchuheng.coding.me.git

# 指定博客分支
branches:
  only:
    - blog

before_install:
  - npm install -g hexo-cli

# Start: Build Lifecycle
install:
  - npm install
  - npm install hexo-deployer-git --save


# 执行清缓存，生成网页操作
script:
  - hexo clean
  - hexo generate
  #gulp压缩文件
  - gulp

# 设置git提交名，邮箱；替换真实token到_config.yml文件，最后depoy部署
after_script:
  - cd ./public
  - git init
  - git config user.name "wuchuheng"
  - git config user.email "root@wuchuheng.com"
  - git add .
  - git commit -m "TravisCI 自动部署"

  # Github Pages
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
  # Coding Pages
  - git push --force --quiet "https://wuchuheng:${CO_TOKEN}@${CO_REF}" master:master
  - git tag v0.0.$TRAVIS_BUILD_NUMBER -a -m "Auto Taged By TravisCI With Build $TRAVIS_BUILD_NUMBER"
  # Github Pages
  - git push --quiet "https://${GH_TOKEN}@${GH_REF}" master:master --tags
  # Coding Pages
  - git push --quiet "https://wuchuheng:${CO_TOKEN}@${CO_REF}" master:master --tags

  # Build Salver Repository(Github Pages)
  #- git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
  # Build Salver Repository(Github Pages)
  #- git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

# End: Build LifeCycle
